\documentclass[12pt]{article}

%%% Be sure to include these two lines in your vignette

%\VignetteEngine{knitr::knitr} 
%\VignetteIndexEntry{dcibioinformatics}

\usepackage[paper=letterpaper,margin=1in]{geometry}

\usepackage{lipsum}
\usepackage{booktabs}
\usepackage{authblk}
\usepackage{enumerate}
\usepackage{amsmath}
\usepackage{amssymb}
\usepackage{multicol}
\usepackage{multirow}
\usepackage{rotating}
\usepackage{longtable}
\usepackage{graphicx}
\usepackage{bm}
\usepackage[compact]{titlesec} 
\titlespacing{\section}{0pt}{0pt}{0pt}
\titlespacing{\subsection}{0pt}{0pt}{0pt}
\usepackage{natbib}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage[scaled]{helvet}
\renewcommand*\familydefault{\sfdefault}
\usepackage[english]{babel}
\usepackage[singlespacing]{setspace}



\newcommand{\R}{\texttt{R}}
\newcommand{\Rfun}[1]{\texttt{#1}}
\newcommand{\Rdat}[1]{\texttt{#1}}
\newcommand{\Rpkg}[1]{\texttt{#1}}
\newcommand{\Rvar}[1]{\texttt{#1}}
\newcommand{\texpkg}[1]{\texttt{#1}}

\setlength{\parskip}{5pt}
\setlength{\parindent}{0pt}


\title{
  A Brief Introduction to \Rpkg{dcibioinformatics}
}
\author{
  Duke Cancer Institute (DCI) Bioinformatics \\
  Duke University Medical Center
}

\begin{document}
\maketitle

\begin{abstract}
  This document is a vignette for using a custom \texttt{R} package
  developed by the Duke Cancer Institute (DCI) Bioinformatics Group.
\end{abstract}

% Configure basic knitr options
<<setup, include=FALSE, cache=FALSE>>=
library(knitr)
# set global chunk options
opts_chunk$set(fig.path='myknitrfigures/', 
               fig.align='center', 
               fig.show='hold',
               out.width = '80%')
options(width=60)
@

% Set the random seed for reproducibility
<<setseed,echo=FALSE>>=
set.seed(123)
@ 


\section*{Session Information}

<<sessioninfo,results="asis", echo=FALSE>>=
toLatex(sessionInfo())
@


%%% Bibliography
\bibliography{dcibioinformatics}
\bibliographystyle{plainnat}

\end{document}
