# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' myrcpp
#' The function illustrates how to use RcppEigen to fit the model
#' Y = X beta + epsilon
#' What is returned is the vector betahat=LSE(beta)
#' @author Kouros Owzar
#' @param Y the vector of response
#' @param X the matrix of covariates (does not include intercept)
#' @return \code{betahat}
#' @export
myrcpp <- function(Y, X) {
    .Call('_dcibioinformatics_myrcpp', PACKAGE = 'dcibioinformatics', Y, X)
}

