# Helper function ----------------------------------------------------------------------

#' countCombine
#' It combines count columns of different samples
#' @import dplyr
#' @param df1 The strand-specific star counts for sample 1
#' @param df2 The strand-specific star counts for sample 2
#' @return The joint df from df1 and df2

countCombine <- function(df1, df2) {
    dplyr::full_join(df1, df2, by="gene")
}



#' mystarfile
#' Generates the full path to a STAR count file.
#' It assume that the count file is of the form
#' rootdir/stardir/suffix
#' @param rootdir The root directory under which the STAR output is stored
#' @param stardir The directory holding the files generated by STAR
#' @param suffix Suffix used by STAR to identify countfile
#' @return Full path to the STAR count file
mystarfile <- function(rootdir, stardir, suffix = "ReadsPerGene.out.tab") {
    file.path(rootdir, stardir, suffix)
}


# Export function -------------------------------------------------------------------
utils::globalVariables(c("stardir","."))

#' getSTARcounts
#' Extract strand-specific STAR counts for each sample and then merge all counts into a single table
#' @import dplyr
#' @import foreach
#' @import readr
#' @param rootdir The root directory under which the count file is stored
#' @param strand The strand-specific protocol used in RNA sequencing. Choose one from \code{c("first", "second", "unstranded")}
#' @return A strand-specific STAR count summary table
#' @export 

getSTARcounts <- function(rootdir,strand) {
    coltypes <- list(col_character(), col_integer(), col_integer(), col_integer())
    stardirs <- list.files(rootdir, full.names = FALSE)
    if(strand == "second"){
        out <- foreach(stardir = stardirs, .combine = countCombine)%do%{
            cntfile <- mystarfile(rootdir, stardir)
                readr::read_tsv(cntfile, col_names = FALSE, col_types = coltypes ) %>%
                    dplyr::select(1, 4) %>%
                        dplyr::rename_at(vars(names(.)),~c("gene",stardir))
        }
    }
    
    else if(strand == "first"){
        out <- foreach(stardir = stardirs, .combine = countCombine)%do%{
            cntfile <- mystarfile(rootdir, stardir)
                readr::read_tsv(cntfile, col_names = FALSE, col_types = coltypes ) %>%
                    dplyr::select(1, 3) %>%
                        dplyr::rename_at(vars(names(.)),~c("gene",stardir))
        }
    }
    
    else if(strand == "unstranded"){
        out <- foreach(stardir = stardirs, .combine = countCombine)%do%{
            cntfile <- mystarfile(rootdir, stardir)
                readr::read_tsv(cntfile, col_names = FALSE, col_types = coltypes ) %>%
                    dplyr::select(1, 2) %>%
                        dplyr::rename_at(vars(names(.)),~c("gene",stardir))
        }
    }
    
    else stop("Missing strand argument! You must specify strand-specific protocol from c('first read strand','second read strand','unstranded')")
    
    if(sum(is.na(out))!= 0)stop("NA exists!")
    out <- out %>% column_to_rownames(var = "gene")
    
    return(out)
}

