
mycombine <- function(df1, df2) {
    full_join(df1, df2, by="gene")
}
#' mystarfile
#' Generates the full path to a STAR count file.
#' It assume that the count file is of the form
#' rootdir/stardir/suffix
#' @param root The root directory under which the count file is stored
#' @param stardir The directory holding the files generated by STAR
#' @param suffix Suffix used by STAR to identify countfile
#' @param X the matrix of covariates (does not include intercept)
#' @return \code{betahat}
mystarfile <- function(rootdir, stardir, suffix = "ReadsPerGene.out.tab") {
    file.path(rootdir, stardir, paste(stardir, suffix, sep=""))
}

getSTARcounts <- function(rootdir, stardirs) {
    coltypes <- list(col_character(), col_integer(), col_integer(), col_integer())

    out <- foreach(stardir = stardirs, .combine = mycombine)%do%{
        cntfile <- mystarfile(rootdir, stardir)
        readr::read_tsv(cntfile, col_names = FALSE, col_types = coltypes ) %>%
            dplyr::select(X1, X4) %>%
                dplyr::rename_(.dots=setNames(names(.), c("gene",stardir)))
    }

    return(out)
}





#' 
#' The function illustrates how to use the myLS Rcpp function
#' from this package from within an R function to fit the model
#' Y = X beta + epsilon 
#' What is returned is the vector betahat=LSE(beta)
#' @param Y the vector of response
#' @param X the matrix of covariates (does not include intercept)
#' @return \code{betahat}
#' @export
getSTARcounts <- function(Y, X) {
    betahat <- myLSrcpp(Y, X)
    return(betahat)
}
